INSERT INTO vegetables (name, image_url, description, native_region, growing_days, row_spacing, spread, sowing_method, tags, water_amount, sun_level, season, height)

VALUES
('Blueberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Apple','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cherry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Lettuce','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cucumber','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Broccoli','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Radish','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'Orange', 30, 'Full Sun','Summer',30),
('Pear','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Straberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Raspberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Banana','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Blueberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Apple','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cherry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Lettuce','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cucumber','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Broccoli','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Radish','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'Orange', 30, 'Full Sun','Summer',30),
('Pear','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Straberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Raspberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Banana','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Blueberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Apple','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cherry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Lettuce','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cucumber','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Broccoli','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Radish','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'Orange', 30, 'Full Sun','Summer',30),
('Pear','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Straberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Raspberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Banana','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Blueberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Apple','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cherry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Lettuce','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Cucumber','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Broccoli','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Radish','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'Orange', 30, 'Full Sun','Summer',30),
('Pear','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Straberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Raspberry','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Banana','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30)

