INSERT INTO vegetables (name, image_url, description, native_region, growing_days, row_spacing, spread, sowing_method, tags, water_amount, sun_level, season, height)
VALUES
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30),
('Tiny Tim Tomato','https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5dc3618ef2c1020004f936e4.jpg?1573085580',
'The tomato is the fruit of the tomato plant, a member of the Nightshade family (Solanaceae). The fruit grows on a small compact bush.',
'Canada', 60, 45, 45, 'Direct seed indoors and transplant seedlings outside after hardening off',
'fruit', 30, 'Full Sun','Summer',30)